#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "questionary>=2.0",
#   "rich>=13",
# ]
# ///
"""CodefyUI-OJ installer wizard.

Runs an interactive setup: environment check → mode (competition/practice) →
config (admin, JWT secret, DB password, ports) → preview .env → write + docker
compose up -d --build. Idempotent: re-running picks up your existing .env as
defaults.

Usage:
    uv run tools/install.py        # full wizard
    uv run tools/install.py --check  # env check only, no prompts
"""
from __future__ import annotations

import argparse
import os
import re
import secrets
import shutil
import socket
import subprocess
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path

import questionary
from questionary import Choice
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

REPO_ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = REPO_ROOT / ".env"
COMPOSE_FILE = REPO_ROOT / "docker-compose.yml"

DEFAULT_FRONTEND_PORT = 8080
DEFAULT_API_PORT = 8100
DEFAULT_DB_PORT = 5432
DEFAULT_REDIS_PORT = 6379

console = Console()


@dataclass
class Settings:
    mode: str = "competition"
    bootstrap_admin: bool = False
    admin_email: str = ""
    admin_password: str = ""
    admin_display_name: str = "Admin"
    db_password: str = field(default_factory=lambda: secrets.token_urlsafe(24))
    jwt_secret: str = field(default_factory=lambda: secrets.token_urlsafe(48))
    frontend_port: int = DEFAULT_FRONTEND_PORT
    cors_origins: str = ""

    def render_env(self) -> str:
        lines = [
            "# Generated by tools/install.py — re-run to regenerate.",
            "# Hand-edits are preserved on re-run as defaults.",
            "",
            f"APP_MODE={self.mode}",
            "",
            "# Postgres",
            "POSTGRES_USER=oj",
            f"POSTGRES_PASSWORD={self.db_password}",
            "POSTGRES_DB=codefyui_oj",
            "",
            "# JWT (rotate for production deployments)",
            f"JWT_SECRET={self.jwt_secret}",
            "",
            f"FRONTEND_PORT={self.frontend_port}",
            f"CORS_ORIGINS={self.cors_origins}",
            "",
            "# Judge: subprocess (false) is fine for dev. true requires the",
            "# sandbox image built via backend/docker/build_sandbox.{ps1,sh}.",
            "JUDGE_USE_DOCKER=false",
        ]
        if self.mode == "competition" and self.bootstrap_admin:
            lines += [
                "",
                "# One-shot admin bootstrap. Removed on first successful boot",
                "# (the resulting user persists in the DB).",
                f"BOOTSTRAP_ADMIN_EMAIL={self.admin_email}",
                f"BOOTSTRAP_ADMIN_PASSWORD={self.admin_password}",
                f"BOOTSTRAP_ADMIN_DISPLAY_NAME={self.admin_display_name}",
            ]
        return "\n".join(lines) + "\n"

    def default_cors_origins(self) -> str:
        port = self.frontend_port
        origins = [f"http://localhost:{port}", f"http://127.0.0.1:{port}"]
        return '[' + ','.join(f'"{o}"' for o in origins) + ']'


# ---------------------------------------------------------------------------
# Existing .env parsing (for re-run defaults)
# ---------------------------------------------------------------------------


_ENV_LINE = re.compile(r"^\s*([A-Z][A-Z0-9_]*)\s*=\s*(.*)$")


def parse_existing_env(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    out: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line or line.lstrip().startswith("#"):
            continue
        m = _ENV_LINE.match(line)
        if not m:
            continue
        key, val = m.group(1), m.group(2).strip()
        # Strip surrounding quotes the way docker compose does.
        if len(val) >= 2 and val[0] == val[-1] and val[0] in ('"', "'"):
            val = val[1:-1]
        out[key] = val
    return out


def settings_from_existing(env: dict[str, str]) -> Settings:
    s = Settings()
    s.mode = env.get("APP_MODE", s.mode)
    if s.mode not in ("competition", "practice"):
        s.mode = "competition"
    s.db_password = env.get("POSTGRES_PASSWORD") or s.db_password
    s.jwt_secret = env.get("JWT_SECRET") or s.jwt_secret
    try:
        s.frontend_port = int(env.get("FRONTEND_PORT") or s.frontend_port)
    except ValueError:
        pass
    s.cors_origins = env.get("CORS_ORIGINS") or s.default_cors_origins()
    s.admin_email = env.get("BOOTSTRAP_ADMIN_EMAIL", "")
    s.admin_password = env.get("BOOTSTRAP_ADMIN_PASSWORD", "")
    s.admin_display_name = env.get("BOOTSTRAP_ADMIN_DISPLAY_NAME", "Admin")
    s.bootstrap_admin = bool(s.admin_email and s.admin_password)
    return s


# ---------------------------------------------------------------------------
# Environment checks
# ---------------------------------------------------------------------------


def _run(cmd: list[str]) -> tuple[bool, str]:
    try:
        out = subprocess.run(cmd, capture_output=True, text=True, check=False, timeout=10)
        if out.returncode != 0:
            return False, (out.stderr or out.stdout or "").strip()
        return True, (out.stdout or "").strip().splitlines()[0] if out.stdout else "ok"
    except (FileNotFoundError, subprocess.TimeoutExpired) as e:
        return False, str(e)


def _port_free(port: int) -> bool:
    # Docker on Windows publishes ports via a userland proxy that doesn't
    # always collide with bind() on 0.0.0.0. The reliable check is "can
    # something accept a connection on localhost:port" — if it accepts or
    # times out (firewalled / loaded), assume in use. Only an explicit
    # ConnectionRefusedError means the port is truly idle.
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.settimeout(1.0)
        try:
            s.connect(("127.0.0.1", port))
        except ConnectionRefusedError:
            return True
        except OSError:
            return False
        return False


def env_checks(ports_to_check: list[int]) -> list[tuple[str, bool, str]]:
    results: list[tuple[str, bool, str]] = []

    if shutil.which("docker") is None:
        results.append(("Docker installed", False, "docker not in PATH"))
    else:
        ok, msg = _run(["docker", "--version"])
        results.append(("Docker installed", ok, msg))

    ok, msg = _run(["docker", "compose", "version"])
    results.append(("docker compose plugin", ok, msg))

    ok, msg = _run(["docker", "info"])
    if ok:
        results.append(("Docker daemon running", True, "ok"))
    else:
        first = msg.splitlines()[0] if msg else "daemon unreachable"
        results.append(("Docker daemon running", False, first))

    for port in ports_to_check:
        free = _port_free(port)
        results.append((f"Port {port} available", free, "free" if free else "already in use"))

    return results


def render_check_table(results: list[tuple[str, bool, str]]) -> Table:
    table = Table(show_header=True, header_style="bold")
    table.add_column("Check")
    table.add_column("Status")
    table.add_column("Detail", overflow="fold")
    for name, ok, detail in results:
        status = "[green]OK[/green]" if ok else "[red]FAIL[/red]"
        table.add_row(name, status, detail)
    return table


# ---------------------------------------------------------------------------
# Wizard steps
# ---------------------------------------------------------------------------


def step_env_check(ports: list[int], non_interactive: bool = False) -> bool:
    console.rule("[bold cyan]Step 1 / Environment check[/bold cyan]")
    results = env_checks(ports)
    console.print(render_check_table(results))

    fatal = [r for r in results if not r[1] and not r[0].startswith("Port")]
    port_warn = [r for r in results if not r[1] and r[0].startswith("Port")]
    if fatal:
        console.print(
            "\n[red]One or more required tools are missing.[/red]\n"
            "Install Docker + the compose plugin and re-run.",
        )
        return False
    if port_warn:
        names = ", ".join(r[0] for r in port_warn)
        console.print(
            f"\n[yellow]Heads up: {names}. The stack will fail to start if these "
            "stay occupied. You can pick a different frontend port in the next step; "
            "DB/Redis/API ports are not configurable here.[/yellow]",
        )
        if non_interactive:
            return True
        if not questionary.confirm("Continue anyway?", default=False).ask():
            return False
    return True


def step_mode(current: Settings) -> str:
    console.rule("[bold cyan]Step 2 / Deployment mode[/bold cyan]")
    return questionary.select(
        "Which install mode?",
        choices=[
            Choice(
                title="Competition — full auth, admin setup, contests, leaderboard",
                value="competition",
                description="Multi-user. Students register / sign in. Admin manages problems and contests.",
            ),
            Choice(
                title="Practice — no login, shared local user, no contests",
                value="practice",
                description="One-machine local use. Skip admin/login entirely.",
            ),
        ],
        default=current.mode,
    ).ask() or current.mode


def step_admin(s: Settings) -> None:
    if s.mode != "competition":
        s.bootstrap_admin = False
        return

    console.rule("[bold cyan]Step 3 / Admin account[/bold cyan]")
    console.print(
        "You have two options for creating the first administrator:\n"
        "  • Pre-create here via env vars (auto-created on first boot)\n"
        "  • Skip and use the [bold]/setup[/bold] UI on first visit to localhost",
    )
    s.bootstrap_admin = questionary.confirm(
        "Pre-create admin now?", default=s.bootstrap_admin
    ).ask() or False

    if not s.bootstrap_admin:
        s.admin_email = ""
        s.admin_password = ""
        return

    s.admin_display_name = questionary.text(
        "Admin display name:",
        default=s.admin_display_name or "Admin",
    ).ask() or "Admin"
    s.admin_email = questionary.text(
        "Admin email:",
        default=s.admin_email,
        validate=lambda v: "@" in v and "." in v.split("@", 1)[1] or "Enter a valid email",
    ).ask() or ""
    s.admin_password = questionary.password(
        "Admin password (≥ 8 chars):",
        validate=lambda v: len(v) >= 8 or "At least 8 characters",
    ).ask() or ""


def step_other(s: Settings) -> None:
    console.rule("[bold cyan]Step 4 / Other settings[/bold cyan]")

    try:
        s.frontend_port = int(
            questionary.text(
                "Frontend port:",
                default=str(s.frontend_port),
                validate=lambda v: v.isdigit() and 1 <= int(v) <= 65535 or "1-65535",
            ).ask()
            or str(s.frontend_port)
        )
    except ValueError:
        pass
    s.cors_origins = s.default_cors_origins()

    use_existing_db = questionary.confirm(
        f"Use generated Postgres password (starts {s.db_password[:6]}…)?",
        default=True,
    ).ask()
    if use_existing_db is False:
        s.db_password = questionary.password("Postgres password:").ask() or s.db_password

    use_existing_jwt = questionary.confirm(
        f"Use generated JWT secret (starts {s.jwt_secret[:6]}…)?",
        default=True,
    ).ask()
    if use_existing_jwt is False:
        s.jwt_secret = questionary.text("JWT secret:").ask() or s.jwt_secret


def _mask(value: str, keep: int = 4) -> str:
    if not value:
        return ""
    return value[:keep] + "•" * 8


def render_preview(s: Settings) -> Table:
    t = Table(show_header=False, box=None, pad_edge=False)
    t.add_column(style="bold")
    t.add_column()
    t.add_row("Mode", s.mode)
    t.add_row("Frontend URL", f"http://localhost:{s.frontend_port}")
    t.add_row("API", f"http://localhost:{DEFAULT_API_PORT}")
    t.add_row("Postgres password", _mask(s.db_password))
    t.add_row("JWT secret", _mask(s.jwt_secret))
    if s.mode == "competition":
        if s.bootstrap_admin:
            t.add_row("Admin", f"{s.admin_email} ({s.admin_display_name})")
            t.add_row("Admin password", _mask(s.admin_password))
        else:
            t.add_row("Admin", "[dim]created via /setup UI on first visit[/dim]")
    else:
        t.add_row("Admin", "[dim]n/a (practice mode)[/dim]")
    return t


def step_preview_and_confirm(s: Settings) -> str:
    """Returns 'install' | 'back' | 'abort'."""
    console.rule("[bold cyan]Step 5 / Preview[/bold cyan]")
    console.print(render_preview(s))
    console.print("\n[dim]Full .env will be written to:[/dim] " + str(ENV_PATH))
    return questionary.select(
        "Proceed?",
        choices=[
            Choice("Yes — write .env and run docker compose up -d --build", value="install"),
            Choice("Back — change a setting", value="back"),
            Choice("Abort — exit without writing", value="abort"),
        ],
    ).ask() or "abort"


# ---------------------------------------------------------------------------
# Install / docker compose orchestration
# ---------------------------------------------------------------------------


def write_env(s: Settings) -> None:
    if ENV_PATH.exists():
        backup = ENV_PATH.with_suffix(ENV_PATH.suffix + ".bak")
        ENV_PATH.replace(backup)
        console.print(f"[dim]Existing .env moved to {backup.name}[/dim]")
    ENV_PATH.write_text(s.render_env(), encoding="utf-8")
    console.print(f"[green]Wrote {ENV_PATH}[/green]")


def docker_compose_up() -> int:
    cmd = ["docker", "compose", "-f", str(COMPOSE_FILE), "up", "-d", "--build"]
    console.print(f"\n[dim]$ {' '.join(cmd)}[/dim]\n")
    proc = subprocess.run(cmd, cwd=str(REPO_ROOT))
    return proc.returncode


def wait_for_health(timeout_sec: int = 120) -> bool:
    import urllib.error
    import urllib.request

    url = f"http://localhost:{DEFAULT_API_PORT}/api/health"
    deadline = time.monotonic() + timeout_sec
    last_err = ""
    with console.status(f"Waiting for {url} to respond …", spinner="dots"):
        while time.monotonic() < deadline:
            try:
                with urllib.request.urlopen(url, timeout=3) as resp:
                    if resp.status == 200:
                        return True
            except (urllib.error.URLError, ConnectionError, TimeoutError) as e:
                last_err = str(e)
            time.sleep(2)
    console.print(f"[red]API did not become healthy within {timeout_sec}s: {last_err}[/red]")
    return False


def show_success(s: Settings) -> None:
    console.rule("[bold green]Install complete[/bold green]")
    front = f"http://localhost:{s.frontend_port}"
    console.print(Panel.fit(
        (
            f"Frontend:  [bold]{front}[/bold]\n"
            f"API:       http://localhost:{DEFAULT_API_PORT}/api/health\n\n"
            + (
                f"[bold]Next:[/bold] open the frontend and create the admin "
                f"via the [bold]/setup[/bold] screen.\n"
                "When done, you can remove the BOOTSTRAP_ADMIN_* lines from .env."
                if s.mode == "competition" and not s.bootstrap_admin
                else (
                    f"[bold]Admin:[/bold] {s.admin_email} (the password you entered).\n"
                    "Remove BOOTSTRAP_ADMIN_* from .env after first successful boot."
                    if s.mode == "competition"
                    else "[bold]Practice mode:[/bold] no login required. "
                         "Open the frontend and start solving."
                )
            )
        ),
        border_style="green",
    ))
    console.print(
        "\nUseful commands:\n"
        "  docker compose logs -f api      # tail API logs\n"
        "  docker compose down             # stop (keep volumes)\n"
        "  docker compose down -v          # stop + wipe DB\n"
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(description="CodefyUI-OJ install wizard")
    parser.add_argument(
        "--check", action="store_true", help="Run environment checks and exit",
    )
    parser.add_argument(
        "--no-up",
        action="store_true",
        help="Write .env but don't run docker compose up at the end",
    )
    args = parser.parse_args()

    console.print(Panel.fit(
        "[bold cyan]CodefyUI-OJ installer[/bold cyan]\n"
        "Interactive setup for the docker compose stack.",
        border_style="cyan",
    ))

    settings = settings_from_existing(parse_existing_env(ENV_PATH))
    if not settings.cors_origins:
        settings.cors_origins = settings.default_cors_origins()

    ports_to_check = [
        settings.frontend_port,
        DEFAULT_API_PORT,
        DEFAULT_DB_PORT,
        DEFAULT_REDIS_PORT,
    ]
    if args.check:
        ok = step_env_check(ports_to_check, non_interactive=True)
        return 0 if ok else 1

    if not step_env_check(ports_to_check):
        return 1

    while True:
        settings.mode = step_mode(settings)
        step_admin(settings)
        step_other(settings)
        # CORS depends on frontend port — recompute after step_other if changed.
        settings.cors_origins = settings.default_cors_origins()

        decision = step_preview_and_confirm(settings)
        if decision == "install":
            break
        if decision == "abort":
            console.print("Aborted. No files written.")
            return 0
        # back: loop

    write_env(settings)
    if args.no_up:
        console.print("[yellow]--no-up: skipping docker compose up.[/yellow]")
        return 0

    rc = docker_compose_up()
    if rc != 0:
        console.print(f"[red]docker compose exited with code {rc}.[/red]")
        return rc

    if not wait_for_health():
        console.print(
            "Stack started but the API isn't responding yet. Check logs with:\n"
            "  docker compose logs -f api",
        )
        return 1

    show_success(settings)
    return 0


if __name__ == "__main__":
    sys.exit(main())
